# Generated by Django 4.2 on 2024-05-18 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_item_item_price_item_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
